version: '3'

networks:
    default:
        external:
            name: home_network

services:
    weather-web:
        build: ./client/
        image: weather.web:local
        container_name: weather-web
        environment:
            - VIRTUAL_HOST=weather.jahiduls.io
        ports:
            - 8080:80
    weather-service:
        build: ./server/
        image: weather.service:local
        container_name: weather-service
        env_file:
            - ./server/.env
        environment:
            - VIRTUAL_HOST=weather-service.jahiduls.io
            - NODE_ENV=production
        ports:
            - 3000:3000

